### ISSUE TITLE
Remove dependency on external API

### ISSUE THREAD

**Issue by chrzrdx** [harsha20599/edyst-s19-diy-pokedex#1]
https://github.com/harsha20599/edyst-s19-diy-pokedex/blob/58f165f0ec74b17555a97d3e1d33a2dd478a6d4f/backend/app.js#L10

Clever solution! 

But, in the case that this external API is down (or they make it a paid service), your API will stop working as well. Can you instead try to store the data locally? Say, to a file called "pokemonData.json" or something? 

You app would read from this file when it starts, and serve requests from the data in it.

**Comment by harsha20599** [comment]
Roger that.

**Comment by harsha20599** [comment]
Updated. Created local file containing data and retrieved from it.
