### ISSUE TITLE
Capture and handle errors on the backend

### ISSUE THREAD

**Issue by chrzrdx** [harsha20599/edyst-s19-diy-pokedex#2]
https://github.com/harsha20599/edyst-s19-diy-pokedex/blob/7ab8fde6e9982b44563a870ee9fd161787bd12f7/backend/app.js#L15

What happens when I access :id > 199 ?

**Comment by harsha20599** [comment]
Roger that! Terenary to the rescue soon.

**Comment by harsha20599** [comment]
Updated id not found error
